name: weather
description: My Weather Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  google_fonts: ^4.0.0
  hydrated_bloc: ^9.0.0
  intl: ^0.18.0
  json_annotation: ^4.4.0
  path_provider: ^2.0.8
  weather_repository:
    path: packages/weather_repository    
  

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
